### ISSUE TITLE
i have a problem on install confluo 

### ISSUE THREAD

**Issue by xiaowuyz** [ucbrise/confluo#111]
Determining if the pthread_create exist failed with the following output:
Change Dir: /root/confluo_test/confluo/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/gmake" "cmTC_6011a/fast"
/usr/bin/gmake -f CMakeFiles/cmTC_6011a.dir/build.make CMakeFiles/cmTC_6011a.dir/build
gmake[1]: Entering directory `/root/confluo_test/confluo/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_6011a.dir/CheckSymbolExists.c.o
/usr/bin/cc    -o CMakeFiles/cmTC_6011a.dir/CheckSymbolExists.c.o   -c /root/confluo_test/confluo/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c
Linking C executable cmTC_6011a
/usr/local/bin/cmake -E cmake_link_script CMakeFiles/cmTC_6011a.dir/link.txt --verbose=1
/usr/bin/cc      -rdynamic CMakeFiles/cmTC_6011a.dir/CheckSymbolExists.c.o  -o cmTC_6011a
CMakeFiles/cmTC_6011a.dir/CheckSymbolExists.c.o: In function `main':
CheckSymbolExists.c:(.text+0x16): undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
gmake[1]: *** [cmTC_6011a] Error 1
gmake[1]: Leaving directory `/root/confluo_test/confluo/build/CMakeFiles/CMakeTmp'
gmake: *** [cmTC_6011a/fast] Error 2

File /root/confluo_test/confluo/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <pthread.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef pthread_create
  return ((int*)(&pthread_create))[argc];
#else
  (void)argc;
  return 0;
#endif
}

Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /root/confluo_test/confluo/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/gmake" "cmTC_f4480/fast"
/usr/bin/gmake -f CMakeFiles/cmTC_f4480.dir/build.make CMakeFiles/cmTC_f4480.dir/build
gmake[1]: Entering directory `/root/confluo_test/confluo/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_f4480.dir/CheckFunctionExists.c.o
/usr/bin/cc   -DCHECK_FUNCTION_EXISTS=pthread_create   -o CMakeFiles/cmTC_f4480.dir/CheckFunctionExists.c.o   -c /usr/local/share/cmake-3.13/Modules/CheckFunctionExists.c
Linking C executable cmTC_f4480
/usr/local/bin/cmake -E cmake_link_script CMakeFiles/cmTC_f4480.dir/link.txt --verbose=1
/usr/bin/cc  -DCHECK_FUNCTION_EXISTS=pthread_create    -rdynamic CMakeFiles/cmTC_f4480.dir/CheckFunctionExists.c.o  -o cmTC_f4480 -lpthreads
/usr/bin/ld: cannot find -lpthreads
collect2: error: ld returned 1 exit status
gmake[1]: *** [cmTC_f4480] Error 1
gmake[1]: Leaving directory `/root/confluo_test/confluo/build/CMakeFiles/CMakeTmp'
gmake: *** [cmTC_f4480/fast] Error 2

**Comment by xiaowuyz** [comment]
solved

**Comment by xiaowuyz** [comment]
new problem:
File /root/confluo_test/confluo/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <pthread.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef pthread_create
  return ((int*)(&pthread_create))[argc];
#else
  (void)argc;
  return 0;
#endif
}

Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /root/confluo_test/confluo/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/gmake" "cmTC_30380/fast"
/usr/bin/gmake -f CMakeFiles/cmTC_30380.dir/build.make CMakeFiles/cmTC_30380.dir/build
gmake[1]: Entering directory `/root/confluo_test/confluo/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_30380.dir/CheckFunctionExists.c.o
/usr/bin/cc   -DCHECK_FUNCTION_EXISTS=pthread_create   -o CMakeFiles/cmTC_30380.dir/CheckFunctionExists.c.o   -c /usr/local/share/cmake-3.13/Modules/CheckFunctionExists.c
Linking C executable cmTC_30380
/usr/local/bin/cmake -E cmake_link_script CMakeFiles/cmTC_30380.dir/link.txt --verbose=1
/usr/bin/cc  -DCHECK_FUNCTION_EXISTS=pthread_create    -rdynamic CMakeFiles/cmTC_30380.dir/CheckFunctionExists.c.o  -o cmTC_30380 -lpthreads
/usr/bin/ld: cannot find -lpthreads
collect2: error: ld returned 1 exit status
gmake[1]: *** [cmTC_30380] Error 1
gmake[1]: Leaving directory `/root/confluo_test/confluo/build/CMakeFiles/CMakeTmp'
gmake: *** [cmTC_30380/fast] Error 2

**Comment by xiaowuyz** [comment]
i already install pthreads
ps -aux | grep pthreads
root     14489  0.0  0.0 112660   972 pts/0    S+   12:36   0:00 grep --color=auto pthreads

**Comment by anuragkh** [comment]
Hi, thanks for trying out Confluo. Can I ask the details of your environment? OS, C++ version, cmake version, etc.?

**Comment by xiaowuyz** [comment]
> Hi, thanks for trying out Confluo. Can I ask the details of your environment? OS, C++ version, cmake version, etc.?

gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

cmake version 3.13.2
CMake suite maintained and supported by Kitware (kitware.com/cmake).

CentOS Linux release 7.4.1708 (Core)

**Comment by xiaowuyz** [comment]
[root@hx3 confluo]# java -version
openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)

**Comment by xiaowuyz** [comment]
gcc-c++-4.8.5-36.el7.x86_64

**Comment by xiaowuyz** [comment]
finally error

-- Boost include dir: Boost_INCLUDE_DIR-NOTFOUND
-- GTest include dir: /root/confluo_test/confluo/build/external/gtest/include
-- GTest static library: /root/confluo_test/confluo/build/external/gtest/lib/libgtest.a
-- GTest main static library: /root/confluo_test/confluo/build/external/gtest/lib/libgtest_main.a
-- Jemalloc library: /root/confluo_test/confluo/build/external/jemalloc/lib/libjemalloc.a
-- Thrift include dir: /root/confluo_test/confluo/build/external/thrift/include
-- Thrift static library: /root/confluo_test/confluo/build/external/thrift/lib/libthrift.a
-- Found PythonInterp: /usr/bin/python (found version "2.7.5")
-- Found setuptools: /usr/lib/python2.7/site-packages/setuptools
CMake Error at /usr/local/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Java (missing: Java_JAR_EXECUTABLE Java_JAVAC_EXECUTABLE
  Java_JAVAH_EXECUTABLE Java_JAVADOC_EXECUTABLE) (found version "1.8.0_191")
Call Stack (most recent call first):
  /usr/local/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/share/cmake-3.13/Modules/FindJava.cmake:331 (find_package_handle_standard_args)
  cmake-modules/Dependencies.cmake:143 (find_package)
  CMakeLists.txt:57 (include)


-- Configuring incomplete, errors occurred!

**Comment by chinlee1523** [comment]
I have the same problem

**Comment by anuragkh** [comment]
You will need `glibc-devel` and `java-1.8.0-openjdk-devel` packages installed; can you make sure those are present?

**Comment by anuragkh** [comment]
Also, for Java, make sure `JAVA_HOME` is set. If you wish to build without Java client support, you can do so by running CMake as follows:

```bash
cmake -DWITH_JAVA_CLIENT=OFF ../
```

**Comment by xiaowuyz** [comment]
That problem has been solved

**Comment by xiaowuyz** [comment]
but  when i make this
have new problem：
[  0%] Creating directories for 'lz4'
[  1%] Performing download step (download, verify and extract) for 'lz4'
-- Downloading...
   dst='/root/confluo_test/confluo/build/lz4-prefix/src/v1.8.2.tar.gz'
   timeout='none'
-- Using src='https://github.com/lz4/lz4/archive/v1.8.2.tar.gz'
-- Retrying...
-- Using src='https://github.com/lz4/lz4/archive/v1.8.2.tar.gz'
-- Retry after 5 seconds (attempt #2) ...
-- Using src='https://github.com/lz4/lz4/archive/v1.8.2.tar.gz'
-- Retry after 5 seconds (attempt #3) ...
-- Using src='https://github.com/lz4/lz4/archive/v1.8.2.tar.gz'
-- Retry after 15 seconds (attempt #4) ...
-- Using src='https://github.com/lz4/lz4/archive/v1.8.2.tar.gz'
-- Retry after 60 seconds (attempt #5) ...
-- Using src='https://github.com/lz4/lz4/archive/v1.8.2.tar.gz'
CMake Error at lz4-stamp/download-lz4.cmake:159 (message):
  Each download failed!

    error: downloading 'https://github.com/lz4/lz4/archive/v1.8.2.tar.gz' failed
         status_code: 1
         status_string: "Unsupported protocol"
         log:
         --- LOG BEGIN ---
         Protocol "https" not supported or disabled in libcurl

  Closing connection -1



         --- LOG END ---
         error: downloading 'https://github.com/lz4/lz4/archive/v1.8.2.tar.gz' failed
         status_code: 1
         status_string: "Unsupported protocol"
         log:
         --- LOG BEGIN ---
         Protocol "https" not supported or disabled in libcurl

  Closing connection -1



         --- LOG END ---
         error: downloading 'https://github.com/lz4/lz4/archive/v1.8.2.tar.gz' failed
         status_code: 1
         status_string: "Unsupported protocol"
         log:
         --- LOG BEGIN ---
         Protocol "https" not supported or disabled in libcurl

  Closing connection -1



         --- LOG END ---
         error: downloading 'https://github.com/lz4/lz4/archive/v1.8.2.tar.gz' failed
         status_code: 1
         status_string: "Unsupported protocol"
         log:
         --- LOG BEGIN ---
         Protocol "https" not supported or disabled in libcurl

  Closing connection -1



         --- LOG END ---
         error: downloading 'https://github.com/lz4/lz4/archive/v1.8.2.tar.gz' failed
         status_code: 1
         status_string: "Unsupported protocol"
         log:
         --- LOG BEGIN ---
         Protocol "https" not supported or disabled in libcurl

  Closing connection -1



         --- LOG END ---
         error: downloading 'https://github.com/lz4/lz4/archive/v1.8.2.tar.gz' failed
         status_code: 1
         status_string: "Unsupported protocol"
         log:
         --- LOG BEGIN ---
         Protocol "https" not supported or disabled in libcurl

  Closing connection -1



         --- LOG END ---




make[2]: *** [lz4-prefix/src/lz4-stamp/lz4-download] Error 1
make[1]: *** [CMakeFiles/lz4.dir/all] Error 2
make: *** [all] Error 2

**Comment by anuragkh** [comment]
How did you install cmake? It seems like cmake wasn’t able to find libssl. You should install the openssl-devel package before installing cmake.

**Comment by chinlee1523** [comment]
> That problem has been solved

hello, how do u solve the problem?thanks!

**Comment by xiaowuyz** [comment]
> > That problem has been solved
> 
> hello, how do u solve the problem?thanks!

i install boost again, then excute cmake -DWITH_JAVA_CLIENT=OFF ../

**Comment by anuragkh** [comment]
Were you able to resolve the cmake issue?

**Comment by xiaowuyz** [comment]
> Were you able to resolve the cmake issue?

i can't find this cmake problem

**Comment by chinlee1523** [comment]
> new problem:
> File /root/confluo_test/confluo/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
> /* */
> #include <pthread.h>
> 
> int main(int argc, char** argv)
> {
> (void)argv;
> #ifndef pthread_create
> return ((int*)(&pthread_create))[argc];
> #else
> (void)argc;
> return 0;
> #endif
> }
> 
> Determining if the function pthread_create exists in the pthreads failed with the following output:
> Change Dir: /root/confluo_test/confluo/build/CMakeFiles/CMakeTmp
> 
> Run Build Command:"/usr/bin/gmake" "cmTC_30380/fast"
> /usr/bin/gmake -f CMakeFiles/cmTC_30380.dir/build.make CMakeFiles/cmTC_30380.dir/build
> gmake[1]: Entering directory `/root/confluo_test/confluo/build/CMakeFiles/CMakeTmp' Building C object CMakeFiles/cmTC_30380.dir/CheckFunctionExists.c.o /usr/bin/cc -DCHECK_FUNCTION_EXISTS=pthread_create -o CMakeFiles/cmTC_30380.dir/CheckFunctionExists.c.o -c /usr/local/share/cmake-3.13/Modules/CheckFunctionExists.c Linking C executable cmTC_30380 /usr/local/bin/cmake -E cmake_link_script CMakeFiles/cmTC_30380.dir/link.txt --verbose=1 /usr/bin/cc -DCHECK_FUNCTION_EXISTS=pthread_create -rdynamic CMakeFiles/cmTC_30380.dir/CheckFunctionExists.c.o -o cmTC_30380 -lpthreads /usr/bin/ld: cannot find -lpthreads collect2: error: ld returned 1 exit status gmake[1]: *** [cmTC_30380] Error 1 gmake[1]: Leaving directory `/root/confluo_test/confluo/build/CMakeFiles/CMakeTmp'
> gmake: *** [cmTC_30380/fast] Error 2

how do u resolve the issue？

**Comment by xiaowuyz** [comment]
sorry,I forgot.Seems to be re-install pthreads

**Comment by xiaowuyz** [comment]
> Were you able to resolve the cmake issue?

I re-install cmake, but still have that problem

**Comment by anuragkh** [comment]
How are you installing cmake? If you are installing from source, you can to do the following:

```bash
nproc=`nproc`
wget https://cmake.org/files/v3.12/cmake-3.12.1.tar.gz
tar xvzf cmake-3.12.1.tar.gz
cd cmake-3.12.1
./configure --system-curl --parallel=$nproc
make -j${nproc}
sudo make install
cd ..
```

**Comment by xiaowuyz** [comment]
Follow your way to reinstall the cmake
"Performing download step (download, verify and extract) for 'lz4'" issue is solved
but make on  "[ 32%] Building CXX object libconfluo/CMakeFiles/confluo.dir/src/confluo_store.cc.o"
has an error:
```
In file included from /usr/local/include/boost/iostreams/detail/is_dereferenceable.hpp:12:0,
                 from /usr/local/include/boost/iostreams/detail/resolve.hpp:26,
                 from /usr/local/include/boost/iostreams/detail/push.hpp:24,
                 from /usr/local/include/boost/iostreams/detail/streambuf/indirect_streambuf.hpp:31,
                 from /usr/local/include/boost/iostreams/stream_buffer.hpp:22,
                 from /usr/local/include/boost/iostreams/stream.hpp:21,
                 from /usr/local/include/boost/spirit/home/qi/stream/detail/iterator_source.hpp:14,
                 from /usr/local/include/boost/spirit/home/qi/stream/stream.hpp:16,
                 from /usr/local/include/boost/spirit/home/qi/stream.hpp:15,
                 from /usr/local/include/boost/spirit/home/qi.hpp:30,
                 from /usr/local/include/boost/spirit/include/qi.hpp:16,
                 from /root/confluo_test/confluo/libconfluo/confluo/parser/aggregate_parser.h:6,
                 from /root/confluo_test/confluo/libconfluo/confluo/aggregate/aggregate_info.h:7,
                 from /root/confluo_test/confluo/libconfluo/confluo/aggregated_reflog.h:5,
                 from /root/confluo_test/confluo/libconfluo/confluo/filter.h:4,
                 from /root/confluo_test/confluo/libconfluo/confluo/archival/load_utils.h:7,
                 from /root/confluo_test/confluo/libconfluo/confluo/atomic_multilog.h:11,
                 from /root/confluo_test/confluo/libconfluo/confluo/confluo_store.h:8,
                 from /root/confluo_test/confluo/libconfluo/src/confluo_store.cc:1:
/usr/local/include/boost/type_traits/detail/bool_trait_def.hpp:18:79: note: #pragma message: NOTE: Use of this header (bool_trait_def.hpp) is deprecated
 # pragma message("NOTE: Use of this header (bool_trait_def.hpp) is deprecated")
                                                                               ^
In file included from /usr/local/include/boost/type_traits/detail/bool_trait_def.hpp:21:0,
                 from /usr/local/include/boost/iostreams/detail/is_dereferenceable.hpp:12,
                 from /usr/local/include/boost/iostreams/detail/resolve.hpp:26,
                 from /usr/local/include/boost/iostreams/detail/push.hpp:24,
                 from /usr/local/include/boost/iostreams/detail/streambuf/indirect_streambuf.hpp:31,
                 from /usr/local/include/boost/iostreams/stream_buffer.hpp:22,
                 from /usr/local/include/boost/iostreams/stream.hpp:21,
                 from /usr/local/include/boost/spirit/home/qi/stream/detail/iterator_source.hpp:14,
                 from /usr/local/include/boost/spirit/home/qi/stream/stream.hpp:16,
                 from /usr/local/include/boost/spirit/home/qi/stream.hpp:15,
                 from /usr/local/include/boost/spirit/home/qi.hpp:30,
                 from /usr/local/include/boost/spirit/include/qi.hpp:16,
                 from /root/confluo_test/confluo/libconfluo/confluo/parser/aggregate_parser.h:6,
                 from /root/confluo_test/confluo/libconfluo/confluo/aggregate/aggregate_info.h:7,
                 from /root/confluo_test/confluo/libconfluo/confluo/aggregated_reflog.h:5,
                 from /root/confluo_test/confluo/libconfluo/confluo/filter.h:4,
                 from /root/confluo_test/confluo/libconfluo/confluo/archival/load_utils.h:7,
                 from /root/confluo_test/confluo/libconfluo/confluo/atomic_multilog.h:11,
                 from /root/confluo_test/confluo/libconfluo/confluo/confluo_store.h:8,
                 from /root/confluo_test/confluo/libconfluo/src/confluo_store.cc:1:
/usr/local/include/boost/type_traits/detail/template_arity_spec.hpp:13:84: note: #pragma message: NOTE: Use of this header (template_arity_spec.hpp) is deprecated
 # pragma message("NOTE: Use of this header (template_arity_spec.hpp) is deprecated")
                                                                                    ^
In file included from /usr/local/include/boost/iostreams/detail/is_dereferenceable.hpp:13:0,
                 from /usr/local/include/boost/iostreams/detail/resolve.hpp:26,
                 from /usr/local/include/boost/iostreams/detail/push.hpp:24,
                 from /usr/local/include/boost/iostreams/detail/streambuf/indirect_streambuf.hpp:31,
                 from /usr/local/include/boost/iostreams/stream_buffer.hpp:22,
                 from /usr/local/include/boost/iostreams/stream.hpp:21,
                 from /usr/local/include/boost/spirit/home/qi/stream/detail/iterator_source.hpp:14,
                 from /usr/local/include/boost/spirit/home/qi/stream/stream.hpp:16,
                 from /usr/local/include/boost/spirit/home/qi/stream.hpp:15,
                 from /usr/local/include/boost/spirit/home/qi.hpp:30,
                 from /usr/local/include/boost/spirit/include/qi.hpp:16,
                 from /root/confluo_test/confluo/libconfluo/confluo/parser/aggregate_parser.h:6,
                 from /root/confluo_test/confluo/libconfluo/confluo/aggregate/aggregate_info.h:7,
                 from /root/confluo_test/confluo/libconfluo/confluo/aggregated_reflog.h:5,
                 from /root/confluo_test/confluo/libconfluo/confluo/filter.h:4,
                 from /root/confluo_test/confluo/libconfluo/confluo/archival/load_utils.h:7,
                 from /root/confluo_test/confluo/libconfluo/confluo/atomic_multilog.h:11,
                 from /root/confluo_test/confluo/libconfluo/confluo/confluo_store.h:8,
                 from /root/confluo_test/confluo/libconfluo/src/confluo_store.cc:1:
/usr/local/include/boost/type_traits/detail/template_arity_spec.hpp:13:84: note: #pragma message: NOTE: Use of this header (template_arity_spec.hpp) is deprecated
 # pragma message("NOTE: Use of this header (template_arity_spec.hpp) is deprecated")
                                                                                    ^
In file included from /root/confluo_test/confluo/libconfluo/../libutils/utils/atomic.h:7:0,
                 from /root/confluo_test/confluo/libconfluo/confluo/archival/archival_utils.h:4,
                 from /root/confluo_test/confluo/libconfluo/confluo/archival/load_utils.h:4,
                 from /root/confluo_test/confluo/libconfluo/confluo/atomic_multilog.h:11,
                 from /root/confluo_test/confluo/libconfluo/confluo/confluo_store.h:8,
                 from /root/confluo_test/confluo/libconfluo/src/confluo_store.cc:1:
/usr/include/c++/4.8.2/atomic: In instantiation of ‘struct std::atomic<confluo::storage::encoded_ptr<unsigned char> >’:
/root/confluo_test/confluo/libconfluo/confluo/storage/swappable_encoded_ptr.h:367:32:   required from ‘class confluo::storage::swappable_encoded_ptr<unsigned char>’
/root/confluo_test/confluo/libconfluo/confluo/container/monolog/monolog_linear_bucket.h:292:22:   required from ‘class confluo::monolog::monolog_linear_bucket<unsigned char, 1048576ul>’
/usr/include/c++/4.8.2/array:97:56:   required from ‘struct std::array<confluo::monolog::monolog_linear_bucket<unsigned char, 1048576ul>, 65536ul>’
/root/confluo_test/confluo/libconfluo/confluo/container/monolog/monolog_linear.h:273:66:   required from ‘class confluo::monolog::monolog_linear_base<unsigned char, 65536ul, 67108864ul, 1048576ul>’
/root/confluo_test/confluo/libconfluo/confluo/container/monolog/monolog_linear.h:282:7:   required from ‘class confluo::monolog::monolog_linear<unsigned char, 65536ul, 67108864ul, 1048576ul>’
/root/confluo_test/confluo/libconfluo/confluo/atomic_multilog.h:539:17:   required from here
/usr/include/c++/4.8.2/atomic:167:7: error: function ‘std::atomic<_Tp>::atomic() [with _Tp = confluo::storage::encoded_ptr<unsigned char>]’ defaulted on its first declaration with an exception-specification that differs from the implicit declaration ‘std::atomic<confluo::storage::encoded_ptr<unsigned char> >::atomic()’
       atomic() noexcept = default;
       ^
/usr/include/c++/4.8.2/atomic: In instantiation of ‘struct std::atomic<confluo::storage::encoded_ptr<long unsigned int> >’:
/root/confluo_test/confluo/libconfluo/confluo/storage/swappable_encoded_ptr.h:367:32:   required from ‘class confluo::storage::swappable_encoded_ptr<long unsigned int>’
/root/confluo_test/confluo/libconfluo/confluo/container/monolog/monolog_exp2_linear.h:54:53:   required from ‘confluo::monolog::monolog_exp2_linear_base<T, NCONTAINERS, BUCKET_SIZE>::~monolog_exp2_linear_base() [with T = long unsigned int; long unsigned int NCONTAINERS = 18ul; long unsigned int BUCKET_SIZE = 1024ul]’
/root/confluo_test/confluo/libconfluo/confluo/container/monolog/monolog_exp2_linear.h:406:7:   required from ‘confluo::string_map<V>::~string_map() [with V = long unsigned int]’
/root/confluo_test/confluo/libconfluo/src/confluo_store.cc:6:57:   required from here
/usr/include/c++/4.8.2/atomic:167:7: error: function ‘std::atomic<_Tp>::atomic() [with _Tp = confluo::storage::encoded_ptr<long unsigned int>]’ defaulted on its first declaration with an exception-specification that differs from the implicit declaration ‘std::atomic<confluo::storage::encoded_ptr<long unsigned int> >::atomic()’
make[2]: *** [libconfluo/CMakeFiles/confluo.dir/src/confluo_store.cc.o] Error 1
make[1]: *** [libconfluo/CMakeFiles/confluo.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by xiaowuyz** [comment]
error in confluo_store.cc.o

**Comment by anuragkh** [comment]
This issue is occurring due to the Boost version 1.53 (see https://github.com/ucbrise/confluo/issues/114). Can you try rebuilding with a more recent Boost version (>= 1.58)?

**Comment by xiaowuyz** [comment]
my boost is  boost_1_61_0.tar.gz

**Comment by anuragkh** [comment]
That's strange. I will try to build it on a CentOS platform and try to reproduce the issue tonight, and get back to you.

**Comment by anuragkh** [comment]
I was able to reproduce the issue you've run into on CentOS 7 with g++ 4.8.5. This is a bug in g++ which was resolved in later g++ versions: https://gcc.gnu.org/bugzilla/show_bug.cgi?format=multiple&id=53901. I've tested the build with g++ 5.3.1 and the compilation completes successfully. You can install g++ 5.3.1 on CentOS 7 as follows:

```bash
sudo yum install centos-release-scl
sudo yum install devtoolset-4-gcc devtoolset-4-gcc-c++
scl enable devtoolset-4 bash
which g++
g++ --version
```

Let me know if that resolves your issue.

**Comment by xiaowuyz** [comment]
thanks you！
