### ISSUE TITLE
Support Golang client and demo.

### ISSUE THREAD

**Issue by forging2012** [ucbrise/confluo#112]
Support Golang client and demo.

**Comment by anuragkh** [comment]
We use thrift as our RPC protocol, so it shouldn't be too difficult to implement it. What is your use-case?

**Comment by forging2012** [comment]
Excellent idea! I will try.
Thanks.

**Comment by anuragkh** [comment]
Please consider creating a PR if you want to contribute the golang client. Thanks for your interest in Confluo!

**Comment by forging2012** [comment]
OK!
Nice project!

**Comment by anuragkh** [comment]
Thanks, closing this issue for now.
