### ISSUE TITLE
How to use Confluo as a pubsub system?

### ISSUE THREAD

**Issue by zzeric** [ucbrise/confluo#113]
The documents do not mention about these, and there is nothing about subscription in the client API.
How to use Confluo as a pubsub system?

**Comment by anuragkh** [comment]
Thanks for your interest in Confluo! We're currently working on exposing a fully functional pub-sub API, there are some minor tests still left to be taken care of. You can find a minimal example with pub-sub API in C++ [here](https://github.com/ucbrise/confluo/tree/single-machine/examples/libstreaming/streaming).
