### ISSUE TITLE
Where to set a maven repo proxy.

### ISSUE THREAD

**Issue by qqqshengwei** [ucbrise/confluo#116]
Hi， I'm trying to make install confluo. However, the installation has some errors to get maven repo. I have a maven proxy (mirror). Where can I set it in the conflue source?

**Comment by anuragkh** [comment]
Can you provide a full CMake build log? The build.xml.in file in javaclient/ needs to be modified to update the maven repository. If you are not planning on using the java client, you can also skip building it as follows:

cmake -DWITH_JAVA_CLIENT=OFF ../

**Comment by qqqshengwei** [comment]
Cool. Thank you very much.
