### ISSUE TITLE
[BUILD] Compile error with CMAKE_BUILD_TYPE=DEBUG

### ISSUE THREAD

**Issue by louishust** [ucbrise/confluo#143]
### What OS are you using?
max os 10.12.6
### What compiler are you using? What version?
(Provide details regarding the type and version of your C/C++ compiler, Java compiler (only for Java client build issues) and Python interpreter (only for Python client build issues).)

```
-- The C compiler identification is AppleClang 9.0.0.9000039
-- The CXX compiler identification is AppleClang 9.0.0.9000039
```

### What's your CMake arguments?
(Provide details regarding the CMake arguments used for Confluo's build.)

```
cmake -DCMAKE_BUILD_TYPE=DEBUG -DWITH_PY_CLIENT=OFF -DWITH_JAVA_CLIENT=OFF  ..
```

### What is the output of the CMake and make commands on a fresh build? (Please sanitize any sensitive information)
(Provide the verbatim logs for CMake and make commands on a fresh build. To obtain a fresh build, remove the contents of the out-of-source build directory before running `cmake` and `make`.)

```
[ 86%] Built target rpcclient
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f librpc/CMakeFiles/rpctest.dir/build.make librpc/CMakeFiles/rpctest.dir/depend
cd /Users/loushuai/research/confluo/bld_debug && /usr/local/Cellar/cmake/3.12.2/bin/cmake -E cmake_depends "Unix Makefiles" /Users/loushuai/research/confluo /Users/loushuai/research/confluo/librpc /Users/loushuai/research/confluo/bld_debug /Users/loushuai/research/confluo/bld_debug/librpc /Users/loushuai/research/confluo/bld_debug/librpc/CMakeFiles/rpctest.dir/DependInfo.cmake --color=
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f librpc/CMakeFiles/rpctest.dir/build.make librpc/CMakeFiles/rpctest.dir/build
make[2]: *** No rule to make target `external/thrift/lib/libthrift.a', needed by `librpc/rpctest'.  Stop.
make[1]: *** [librpc/CMakeFiles/rpctest.dir/all] Error 2
```

**Comment by anuragkh** [comment]
Fixed in https://github.com/ucbrise/confluo/pull/144
